### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by mansya** [aniketbhoite/BMI-calculator-Kotlin-Room-MVP#2]
Hi, @aniketbhoite I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by aniketbhoite** [comment]
Why not? I would love to see it

**Comment by mansya** [comment]
I have design a logo for this app. what do you think ? do you like it ?
![bmi calculator kotlin room mvp](https://user-images.githubusercontent.com/33461607/41229109-00b31bc0-6da5-11e8-89f9-69a36d5daf15.png)

**Comment by aniketbhoite** [comment]
This is a demo app so it doesn't have a unique color scheme but the primary color is blue. So can you make logos in blue color or design an entire app using logo's colors

**Comment by mansya** [comment]
I will design blue logo. can you give me the RGB color code?

**Comment by aniketbhoite** [comment]
#3F51B5

**Comment by mansya** [comment]
I have uploaded all file to this link
https://drive.google.com/open?id=1RP7W4UNHpRdrxBbH-fr3Wtk-LNLrzKJY

and I have sent you Pull requests. please check.

**Comment by aniketbhoite** [comment]
Thank you for files and your contributions, I added launcher icon also.
